=pod

=begin :comment

Copyright (C)  2013  Zoltan Vass <zoltan.tombol (at) gmail (dot) com>

This manual is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

=end :comment

=head1 NAME

photo-man.pl - A simple photo management utility written in Perl 5 for the
Linux command-line

=head1 VERSION

VERSION 0.2

=head1 SYNOPSIS

photo-man.pl [OPTIONS] FILE...

=head1 DESCRIPTION

B<photo-man> is a free and open-source utility aiming to simplify command-line
based photo management on the Linux platform.

B<photo-man> can move and rename images according to a user specified template
referencing parts of the C<EXIF DateTimeDigitized> timestamp,
set files' modification time to C<EXIF DateTimeDigitized> shifted to the
local time zone,
and determine the correct extension using the magic number.

The utility uses the excellent L<Image::ExifTool> module to access metadata
embedded in image files.

B<photo-man> and this documentation is licensed under GPL version 3.

=head1 ARGUMENTS

The script takes one or more files as arguments. Files can be specified by name
or as globs.

    photo-man --rename 'img-%Y%m%d-%H%M%S' beach.jpeg ~/photos/*.jpg

The order of processing is determined by the system's locale.

=head1 OPTIONS

Mandatory arguments to long options are mandatory for short options too.

=head2 Operations

=over

=item -m, --move=TEMPLATE

Move files to new locations specified by C<TEMPLATE>, a string containing any
character allowed in a path by the file system and
L<strtime format strings|DateTime/"strftime Patterns"> referencing parts of
C<EXIF DateTimeDigitized>.
File names are preserved and directories are created as necessary.

For example, the command below will move all images with 'jpeg' extension in
the current directory to separate directories based on which year, month and
day they were taken.

    photo-man -m '%Y/%m.%d' *.jpeg

This command would make the following changes, assuming the files on the left
match the criteria and their timestamps are the ones given on the right.

    file                moved to                    DateTimeDigitized
    --------------      -------------------------   -------------------
    ./image-1.jpeg  ->  ./2013/07.21/image-1.jpeg   2013-07-21 16:21:43
    ./image-2.jpeg  ->  ./2013/06.30/image-2.jpeg   2013-06-30 08:32:00
    ./image-3.jpeg  ->  ./2013/07.21/image-3.jpeg   2013-07-21 11:44:05

=item -r, --rename=TEMPLATE

Rename files to new file names specified by C<TEMPLATE>, a string containing
any character allowed in a file name by the file system and
L<strtime format strings|DateTime/"strftime Patterns"> referencing parts of
C<EXIF DateTimeDigitized>.
Files are renamed in-place and left at their original location.

For example, the command below will rename all images with 'jpeg' extension in
the current directory to names containing the date and time they were taken.

    photo-man -r 'img-%Y%m%d-%H%M%S' *.jpeg

This command would make the following changes, assuming the files on the left
match the criteria and their timestamps are the ones given on the right.

    file                renamed to                   DateTimeDigitized
    --------------      --------------------------   -------------------
    ./image-1.jpeg  ->  ./img-20130721-162143.jpeg   2013-07-21 16:21:43
    ./image-2.jpeg  ->  ./img-20130630-083200.jpeg   2013-06-30 08:32:00
    ./image-3.jpeg  ->  ./img-20130721-114405.jpeg   2013-07-21 11:44:05

C<TEMPLATE> does not contain the extension which is automatically appended to
new file names. By default the substring after the last dot of the file name is
used as the extension.
The extensions can also be determined from the file's magic number instead. See
C<--use-magic> below for details.

=item -t, --touch=TIME_ZONE

Set the file system modification timestamp of files to
C<EXIF DateTimeDigitized> shifted into the local time zone. The C<TIME_ZONE>
argument is the time zone of the location where the photo was taken. This
arguments has to be supplied manually as EXIF can not handle time zone
information. It can be given in a format recognised by
L<DateTime|DateTime/"DateTime-E<gt>new(_..._)">. The following two commands
mean the same.

    photo-man -t 'Asia/Tokyo' photos/*.jpeg     # Olson DB time zone name
    photo-man -t '+0900' photos/*.jpeg          # offset string

For example, if the command above is issued on a machine whose local time zone
is set to 'Europe/Budapest' in daylight saving mode (i.e. +0200), the
modification timestamp would be set as shown on the right, assuming the files
on the left match the criteria and their timestamps are the ones given in the
middle,

    file             DateTimeDigitized     Modification time
    --------------   -------------------   -----------------------------------
    ./image-1.jpeg   2013-07-21 16:21:43   2013-07-21 09:21:43.000000000 +0200
    ./image-2.jpeg   2013-06-30 06:32:00   2013-06-29 23:32:00.000000000 +0200

If shifting the timestamps into the local time zone is not desirable, one can
specify C<local> as the original time zone, in which case the EXIF timestamp is
used directly without first shifting it into the local time zone.

=back

=head2 Operation modifiers

=over

=item -u, --use-magic

By default the extension in a C<--rename> operation is determined by the
portion of the file name after the last dot.
This behaviour is altered when using C<--use-magic> and the file's magic number
is used to determine the extension.

For example, the command below will rename all images in the current whose file
name starts 'IMG' while determining the extensions using the files' magic
number.

    photo-man -u -r 'img-%Y%m%d-%H%M%S' IMG*

This command would make the following changes, assuming the files on the left
match the criteria and their timestamps are the ones given on the right.

    file               renamed to                   DateTimeDigitized
    -------------      --------------------------   -------------------
    ./image-1.JPG  ->  ./img-20130721-162143.jpeg   2013-07-21 16:21:43
    ./image-2.jpg  ->  ./img-20130630-083200.jpeg   2013-06-30 08:32:00
    ./image-3.jpe  ->  ./img-20130721-114405.jpeg   2013-07-21 11:44:05

It is also possible to use C<--rename> without a C<TEMPLATE> together with
C<--use-magic> to only correct the extensions and do not rename files.
Note that the C<--> is necessary to prevent C<IMG*> to be interpreted as an
argument to C<-r>.

    photo-man -u -r -- IMG*

This command would make the following changes on the same set of files.

    file               renamed to       DateTimeDigitized
    -------------      --------------   -------------------
    ./image-1.JPG  ->  ./image-1.jpeg   2013-07-21 16:21:43
    ./image-2.jpg  ->  ./image-2.jpeg   2013-06-30 08:32:00
    ./image-3.jpe  ->  ./image-3.jpeg   2013-07-21 11:44:05

Also using C<--use-magic> is the only case where the argument to C<--rename>
can be omitted.

=back

=head2 Processing modes

=over

=item -c, --commit

Make the listed changes to the file system. By default, B<photo-man> performs a
dry-run that only outputs what would have been done, without making any changes
to the file system. This dry-run can be used to tune the command until the
desired outcome is achieved, before committing the changes to the file system.

=item -f, --force

Execute irreversible operations. To avoid data loss, irreversible operations,
such as overwriting files, are performed only when this option is explicitly
specified. By default, destructive operations are not executed, only reported.

=back

=head2 Output control

=over

=item -v, --verbose

Produce verbose output. By default, a compact and concise output format is
used.

=back

=head2 Generic program information

=over

=item -h, --help

Display usage information and exit.

=item --man

Display complete documentation and exit.

=back

=head1 BUGS

=head2 Bug reporting

Bug reports can be submitted via B<photo-man>'s issue tracker on GitHub at
<https://github.com/ztombol/photo-man/issues>.

=head1 COPYRIGHT

B<photo-man>, including test assets such as image files, and this manual is
licensed under GPL version 3.

You should have received a copy of the GNU General Public License along with
B<photo-man>. If not, see <http://www.gnu.org/licenses/>.

=head1 AUTHOR

Zoltan Vass <zoltan.tombol (at) gmail (dot) com>

=cut
